### ISSUE TITLE
Django project setup

### ISSUE THREAD

**Issue by AdrianDAlessandro** [AdrianDAlessandro/rse-competencies-toolkit-webapp#6]
- [ ] Create a Django Project and main app
- [ ] Configure Django Settings
- [ ] Add Docker setup
- [ ] Create custom User model
- [ ] Add index Page
- [ ] Configure for testing with pytest-django
- [ ] Configure Docker setup

**Comment by AdrianDAlessandro** [comment]
@davehorsfall Apologies for not tagging you in this or the PRs that closed the first two issues. I'll tag you from now on, if you're interested in what's been done so far, there should be some detail in the issues and the PRs themselves. If you have any questions, let me know.
